name: CI

on:
  push:

  pull_request:

env:
  ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true

jobs:
  ci:
    name: ${{ matrix.hwVersion }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hwVersion: [HW6]

    steps:
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install libraries
        run: |
          arduino-cli lib install \
            "SdFat" \
            "Adafruit SSD1306" \
            "Adafruit GFX Library" \
            "Adafruit BusIO" \
            "RTClib" \
            "FreqCount"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd code-arduino/
          # Select hardware version by uncommenting it (using regular expression)
          sed -i 's/^\/\/[\t ]*#define ${{ matrix.hwVersion }}/#define ${{ matrix.hwVersion }}/g' pindeclarations.h
          arduino-cli compile --fqbn arduino:avr:mega --warnings all
